### ISSUE TITLE
Emotional Facial Expression Database of Animation Units

### ISSUE THREAD

**Issue by colceagus** [nelsonam/thesis-facetracking#1]
Hi Allison, 

I'm writing my research paper (and after, my dissertation) and I don't have time to build my own emotional facial expression database. I only have 2 persons and I use the Animation Units for training my classifiers. 
Would you please be so cool and share your database, I will cite you in my article. I'm kind of desperate. Please respond asap.

With all my gratitude,
Daniel Colceag.

PS:  I also wrote on your blog, but I guess you didn't see the comment due to the huge amount of mail you receive every day.

**Comment by nelsonam** [comment]
Hi Daniel, I apologize for missing your messages. I've somehow not been receiving notifications of comments on my blog. What exactly do you need?

**Comment by colceagus** [comment]
Hi Allison, 

I would like to train my emotion recognition neural network on your database combined with mine (i only have a couple of persons now) and another one that I will try to extract from a 2k people database the FACS Action Units with some other SDK and match them against the Kinect Animation Units. 

Do you think you could share your database with me ? I promise to mention your research paper in my research paper and add a thank you.

**Comment by colceagus** [comment]
Hi Allison, 

I am waiting for a positive outcome on this matter. When do you think you can prepare a DB backup for me ? 

Kind Regards, 
Daniel.

**Comment by colceagdaniel** [comment]
Hi Allison, 

Could you please respond to my request? I need to know either if you can or cannot provide some help with te training database.

Thanks,
Daniel

**Comment by nelsonam** [comment]
Hi Daniel,

Unfortunately, I no longer have access to those files. I know that the Kinect library has changed a lot over this time as well, as I did my work with the old PC Kinect. I hope that your work continues to go well, and thanks for stopping by.

-Al

**Comment by colceagus** [comment]
I am using the old Kinect though. Can you do some 'magic' to revive them? 
How large was the dataset? How many persons? I knew this info an I've forgotten it.
